packages = ["pandas"]

[[fetch]]
files = [
    "scripts/data_loader.py",
    "scripts/game_processing.py",
    "scripts/scouting_tool.py",
    "data/era_plus_rules.md",
    "data/fip_rules.md",
    "data/gamelogs.txt",
    "data/ops_plus_rules.md",
    "data/pitching_stat_rules.md",
    "data/re24_rules.md",
    "data/war_rules.md",
    "data/cache/cache_info.json",
    "data/cache/hitting_stats_S1.csv",
    "data/cache/hitting_stats_S10.csv",
    "data/cache/hitting_stats_S11.csv",
    "data/cache/hitting_stats_S2.csv",
    "data/cache/hitting_stats_S3.csv",
    "data/cache/hitting_stats_S4.csv",
    "data/cache/hitting_stats_S5.csv",
    "data/cache/hitting_stats_S6.csv",
    "data/cache/hitting_stats_S7.csv",
    "data/cache/hitting_stats_S8.csv",
    "data/cache/hitting_stats_S9.csv",
    "data/cache/pitching_decisions_S1.csv",
    "data/cache/pitching_decisions_S10.csv",
    "data/cache/pitching_decisions_S11.csv",
    "data/cache/pitching_decisions_S2.csv",
    "data/cache/pitching_decisions_S3.csv",
    "data/cache/pitching_decisions_S4.csv",
    "data_cache/pitching_decisions_S5.csv",
    "data/cache/pitching_decisions_S6.csv",
    "data/cache/pitching_decisions_S7.csv",
    "data/cache/pitching_decisions_S8.csv",
    "data/cache/pitching_decisions_S9.csv",
    "data/cache/pitching_stats_S1.csv",
    "data/cache/pitching_stats_S10.csv",
    "data/cache/pitching_stats_S11.csv",
    "data/cache/pitching_stats_S2.csv",
    "data/cache/pitching_stats_S3.csv",
    "data/cache/pitching_stats_S4.csv",
    "data/cache/pitching_stats_S5.csv",
    "data/cache/pitching_stats_S6.csv",
    "data/cache/pitching_stats_S7.csv",
    "data/cache/pitching_stats_S8.csv",
    "data/cache/pitching_stats_S9.csv",
    "data/cache/re_matrix_S1.csv",
    "data/cache/re_matrix_S10.csv",
    "data/cache/re_matrix_S11.csv",
    "data/cache/re_matrix_S2.csv",
    "data/cache/re_matrix_S3.csv",
    "data/cache/re_matrix_S4.csv",
    "data/cache/re_matrix_S5.csv",
    "data/cache/re_matrix_S6.csv",
    "data/cache/re_matrix_S7.csv",
    "data/cache/re_matrix_S8.csv",
    "data/cache/re_matrix_S9.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S1.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S10.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S11.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S2.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S3.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S4.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S5.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S6.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S7.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S8.csv",
    "data/cache/raw_gamelogs/raw_gamelog_S9.csv"
]
