import pandas as pd
from get_hitting_stats import _calculate_hitting_rate_stats, _calculate_ops_plus
from get_pitching_stats import _calculate_pitching_rate_stats, _calculate_era_minus

def create_hitting_subrows(hitting_stats):
    '''
    Function for creating multi-team seasons stat rows and assigning the individual teams as subrows.
        hitting_stats - dataframe of hitting stats generated by get_hitting_stats(gamelog_df, 'season') from get_hitting_stats.py

    Output:
        hitting_stats - dataframe with 'is_sub_row' column and multi-team season stats
    '''
    
    hitting_stats['is_sub_row'] = False # preliminarily assign False to all rows

    multi_teams = hitting_stats[hitting_stats.duplicated(subset = ['ID', 'Season'], keep = False)] # find multi-team seasons
    multi_teams['count'] = 1 # add a counter

    hitting_stats.loc[hitting_stats.index.isin(multi_teams.index), 'is_sub_row'] = True # set subrow to True for any multi-team seasons

    # counting stats
    cols = ['HR', '3B', '2B', '1B', 'BB', 'IBB', 'FO', 'SO', 'Auto K', 'PO', 'RGO', 'LGO', 'LO',
            'SF', 'SH', 'GO', 'GIDP', 'GITP', 'SB', 'CS', 'H', 'PA', 'AB', 'TB', 'G', 'R', 'RBI',
            '1RHR', '2RHR', '3RHR', '4RHR', 'TB+', 'H_RISP', 'AB_RISP',
            'Total Diff', 'Total Plays', 'RE24', 'WPA', 'WAR', '0 Diffs', '500 Diffs',
            'nH', 'nTB', 'nBB', 'nFO', 'nSH', 'nPA', 'nAB', 'nSF', 'count']

    # stats that are the same for all relevant rows
    lgn_cols = ['SF value', 'lgnH', 'lgnBB', 'lgnPA', 'lgnAB', 'lgnTB', 'lgnOBP', 'lgnSLG', 'Last Team', 'Last Session', 'Batting Type', 'Pitching Type', 'Handedness', 'Position', 'Display Season', 'Name']
    
    combined_seasons = multi_teams.groupby(['ID', 'Season'])[cols].sum().reset_index() # sum counting stats
    combined_lgn = multi_teams.groupby(['ID', 'Season'])[lgn_cols].first().reset_index() # take the first of constant values

    # recalculate rate stats
    combined_seasons = _calculate_hitting_rate_stats(combined_seasons)

    # populate team column for combined seasons
    combined_seasons['Team'] = combined_seasons['count'].astype(str) + 'TM'
    combined_seasons['Franchise'] = combined_seasons['Team']
    combined_seasons = combined_seasons.drop(columns = 'count')
    
    combined_seasons['is_sub_row'] = False # combined rows are not subrows
    
    combined_seasons = combined_seasons.merge(combined_lgn, on = ['ID', 'Season']) # merge counting/rate stats dataframe with constant values dataframe
    combined_seasons = _calculate_ops_plus(combined_seasons) # calculate OPS+

    # concatenate dataframes to have combined seasons. Important to concatenate in this order for displaying on the site
    hitting_stats = pd.concat([combined_seasons, hitting_stats], ignore_index = True)

    # sort and reindex
    hitting_stats = hitting_stats.sort_values(['ID', 'Season', 'Last Session']).reset_index(drop = True)

    return hitting_stats


def create_pitching_subrows(pitching_stats):
    '''
    Function for creating multi-team seasons stat rows and assigning the individual teams as subrows.
        hitting_stats - dataframe of hitting stats generated by get_hitting_stats(gamelog_df, 'season') from get_hitting_stats.py

    Output:
        hitting_stats - dataframe with 'is_sub_row' column and multi-team season stats
    '''

    '''
    Function for creating multi-team seasons stat rows and assigning the individual teams as subrows.
        hitting_stats - dataframe of hitting stats generated by get_hitting_stats(gamelog_df, 'season') from get_hitting_stats.py

    Output:
        hitting_stats - dataframe with 'is_sub_row' column and multi-team season stats
    '''
    
    pitching_stats['is_sub_row'] = False # preliminarily assign False to all rows

    multi_teams = pitching_stats[pitching_stats.duplicated(subset = ['ID', 'Season'], keep = False)] # find multi-team seasons
    multi_teams['count'] = 1 # add a counter

    pitching_stats.loc[pitching_stats.index.isin(multi_teams.index), 'is_sub_row'] = True # set subrow to True for any multi-team seasons

    # counting stats
    cols = ['HR', '3B', '2B', '1B', 'BB', 'IBB', 'Auto BB', 'FO', 'SO', 'PO', 'RGO', 'LGO', 'LO',
            'SF', 'SH', 'GO', 'DP', 'TP', 'SB', 'CS', 'H', 'IP', 'BF', 'AB', 'TB', 'G', 'ER', 
            'Total Diff', 'Total Plays', 'RE24', 'WAR', 'WPA', '0 Diffs', '500 Diffs', '300+ Pitches', '400+ Pitches',
            'W', 'L', 'SV', 'HLD', 'BS', 'GS', 'GF', 'CG', 'SHO', 'OPP', 'nER', 'nIP', 'count']

    # stats that are the same for all relevant rows
    lgn_cols = ['FIP Constant', 'lgnER', 'lgnIP', 'lgnERA', 'Last Team', 'Last Session', 'Batting Type', 'Pitching Type', 'Pitching Type (Main)', 'Handedness', 'Position', 'Display Season', 'Name']
    
    combined_seasons = multi_teams.groupby(['ID', 'Season'])[cols].sum().reset_index() # sum counting stats
    combined_lgn = multi_teams.groupby(['ID', 'Season'])[lgn_cols].first().reset_index() # take the first of constant values

    # populate team column for combined seasons
    combined_seasons['Team'] = combined_seasons['count'].astype(str) + 'TM'
    combined_seasons['Franchise'] = combined_seasons['Team']
    combined_seasons = combined_seasons.drop(columns = 'count')
    
    combined_seasons['is_sub_row'] = False # combined rows are not subrows
    
    combined_seasons = combined_seasons.merge(combined_lgn, on = ['ID', 'Season']) # merge counting/rate stats dataframe with constant values dataframe

    # recalculate rate stats
    combined_seasons = _calculate_pitching_rate_stats(combined_seasons)
    
    combined_seasons = _calculate_era_minus(combined_seasons) # calculate ERA-

    # concatenate dataframes to have combined seasons. Important to concatenate in this order for displaying on the site
    pitching_stats = pd.concat([combined_seasons, pitching_stats], ignore_index = True)

    # sort and reindex
    pitching_stats = pitching_stats.sort_values(['ID', 'Season', 'Last Session']).reset_index(drop = True)

    return pitching_stats