
name: Update Web Data

on:
  schedule:
    - cron:  '0 6 * * *' # Runs every day at midnight CT (6:00 UTC).
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Or whatever version you use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script to generate web data
      run: python scripts/generate_web_data.py

    - name: Commit and push if there are changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated update of web data"
        file_pattern: docs/data/*.json
